# Generated by Django 3.2.6 on 2021-08-12 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Menu',
        ),
    ]
